name = "red-packet-spa-backend"
main = "src/worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
JWT_SECRET = "your-secret-key-change-in-production"
JWT_EXPIRES_IN = "7d"
DOMAIN = "your-domain.com"